src/conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'', include('pages.urls', namespace='pages')),
    url(r'', include('account.urls', namespace='account')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

src/pages/urls.py
# coding:utf-8
from django.conf.urls import patterns, url
from views import IndexView, OrderView

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^pattern/(?P<type>\w+)/$', OrderView.as_view(), name='order'),
)

src/pages/templates/pages/index.html
{% extends 'base.html' %}
{% load webdesign %}

{% block title %}Главная - Redstack{% endblock %}

{% block ng-app %}UserApp{% endblock %}

{% block main %}
    <div class="title_wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>Выберите Ваш план</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>{% lorem 10 w random %}</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="price_wrap">
        <div class="container">
            <div class="row">
                {% for tariff in tariffs %}
                    <div class="col-md-4 first">
                        <div class="p_title text-center">
                            <span class="rub">a </span>{{ tariff.price }}<span>.00</span><br/>
                            <h5><strong>{{ tariff.name }}</strong></h5>
                        </div>
                        <div class="p_content text-center">
                            <ul class="list-unstyled">
                                {% for ben in tariff.benefits.all %}
                                    <li>
                                        <span class="glyphicon glyphicon-{{ ben.icon }}"></span>&nbsp;&nbsp;<span>{{ ben.name }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                            <a href="{% url 'pages:order' tariff.slug %}" class="btn btn-success"
                               role="button">Выбрать</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="extra_wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2>Преимущества</h2>
                </div>
            </div>
            <div class="row e_list">
                <div class="el_column col-md-2 col-md-offset-4">
                    <ul class="list-unstyled">
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                    </ul>
                </div>
                <div class="el_column col-md-3 el_last">
                    <ul class="list-unstyled">
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                        <li><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;{% lorem 2 w random %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}css/index{% if not debug %}.min{% endif %}.css" rel="stylesheet">
{% endblock %}
{% block extra_js %}{% endblock %}

src/pages/templates/pages/pattern.html
{% extends 'base.html' %}
{% load webdesign %}

{% block title %}Выбор шаблона - Redstack{% endblock %}

{% block ng-app %}PatternApp{% endblock %}

{% block main %}
    <div class="page_wrap">
        <div class="container">
            <div class="row title_wrap">
                <div class="col-md-12 text-center">
                    <h1>Выбор шаблона</h1>
                </div>
            </div>
            {% if patterns %}
                {% with form_name='PatternForm' %}
                    <form name="{{ form_name }}" ng-submit="form.submit('{{ request.path }}')"
                          ng-controller="{{ form_name }}Ctrl" role="form" ng-cloak>
                        {% csrf_token %}
                        <div class="alert alert-danger" ng-show="form.errors.__all__">
                            <span ng-repeat="err in form.errors.__all__">[% err %]<br/></span>
                        </div>

                        <div class="row input_wrap">
                            <span ng-repeat="err in form.errors.name" style="color:#8A6D3B;">[% err %]<br/></span>

                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-3 field">
                                    <input name="name" ng-model="form.fields.name" class="form-control"
                                           placeholder="Название сайта" type="text" required>
                                <span ng-show="form.errors.name"
                                      class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                                </div>
                                <div class="col-md-2 field">
                                    <button class="btn btn-success btn-block" type="button" ng-click="generate_name()">
                                        Случайное
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="row pattern_wrap" ng-init="blurs=build({{ patterns|length }})">
                            <span ng-repeat="err in form.errors.pattern" style="color:#8A6D3B;">[% err %]<br/></span>

                            {% for pattern in patterns %}
                                <div class="col-xs-12 col-md-4 pw_item">
                                    <img src="{{ pattern.img.url }}" ng-class="blurs.{{ forloop.counter0 }}"
                                         ng-mouseenter="active({{ forloop.counter0 }})" ng-mouseleave="deactive()"
                                         ng-click="set_img('{{ pattern.id }}')" class="img-rounded img-responsive">
                                    <input name="pattern" ng-model="form.fields.pattern" type="radio"
                                           value="{{ pattern.id }}" ng-checked="form.fields.pattern"
                                           ng-required="!form.fields.pattern">
                                </div>
                            {% endfor %}
                        </div>

                        <div class="row button_wrap">
                            <div class="col-md-2 col-md-offset-5">
                                <button class="btn btn-success btn-block [% form.loader.selector %] ladda-button"
                                        ng-disabled="{{ form_name }}.$invalid" data-style="zoom-out">Создать
                                </button>
                            </div>
                        </div>
                    </form>
                {% endwith %}
            {% else %}
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h3>По выбранному тарифу шаблонов не найдено</h3>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}css/pattern{% if not debug %}.min{% endif %}.css" rel="stylesheet">
{% endblock %}
{% block extra_js %}
    <script src="{{ STATIC_URL }}js/pages{% if not debug %}.min{% endif %}.js"></script>
{% endblock %}