src/account/urls.py
# coding:utf-8
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^registration/$', views.RegistrationView.as_view(), name='registration'),

    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_change/$', views.PasswordChangeView.as_view(), name='password_change'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
)

src/conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'', include('pages.urls', namespace='pages')),
    url(r'', include('account.urls', namespace='account')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

src/pages/urls.py
# coding:utf-8
from django.conf.urls import patterns, url
from views import IndexView, OrderView

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^pattern/(?P<type>\w+)/$', OrderView.as_view(), name='order'),
)

src/templates/base.html
{% load webdesign %}
{% load user_filters %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Redstack{% endblock %}</title>
</head>
<body ng-app="{% block ng-app %}{% endblock %}">
<div class="body_wrap">
    <div class="content_wrap">
        <header ng-controller="SignCtrl">
            <div class="container">
                <div class="row">
                    <div class="h_logo col-xs-5 col-sm-5 col-md-3">
                        <a href="{% url 'pages:index' %}" class="not-hover"><strong><span>RED</span>stack</strong></a>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="h_user col-xs-3 col-sm-3 col-md-2 pull-right">
                            <button type="button" ng-click="logout('{% url 'account:logout' %}')"
                                    class="btn btn-entry btn-block">Выйти
                            </button>
                        </div>
                        <div class="h_user col-xs-4 col-sm-4 col-md-3 pull-right">
                            <div class="h_email">
                                <span class="glyphicon glyphicon-user"></span>&nbsp;
                                <a href="{% url 'account:profile' %}">{{ user|display }}</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="h_user col-xs-3 col-sm-3 col-md-2 pull-right">
                            <button type="button" ng-click="login()" class="btn btn-entry btn-block">Войти</button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </header>
        {% block main %}{% endblock %}
    </div>
    <footer>
        <div class="footer_wrap">
            <div class="ft_wrap">
                <div class="container">
                    <div class="row">
                        <div class="ft_logo col-md-3">
                            <strong><span>RED</span>stack</strong>
                        </div>
                        <div class="ft_block col-md-3">
                            <h4>{% lorem 1 w random %}</h4>
                            <ul class="list-unstyled">
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                            </ul>
                        </div>
                        <div class="ft_block col-md-3">
                            <h4>{% lorem 1 w random %}</h4>
                            <ul class="list-unstyled">
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                                <li><a href="">{% lorem 1 w random %}</a></li>
                            </ul>
                        </div>
                        <div class="ft_block col-md-3">
                            <h4>{% lorem 1 w random %}</h4>
                            <ul class="list-unstyled">
                                <li><span class="glyphicon glyphicon-remove-circle"></span>&nbsp;&nbsp;<a
                                        href="">{% lorem 2 w random %}</a></li>
                                <li><span class="glyphicon glyphicon-ok-circle"></span>&nbsp;&nbsp;<a
                                        href="">{% lorem 2 w random %}</a></li>
                                <li><span class="glyphicon glyphicon-ban-circle"></span>&nbsp;&nbsp;<a
                                        href="">{% lorem 2 w random %}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="fb_wrap">
                <div class="container">
                    <div class="row">
                        <div class="fb_copy col-md-5">
                            Copyright © Redstack 2014 Все права защищены
                        </div>
                        <div class="fb_author"></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

{% include 'account/incl/enter_popup.html' %}

<link href="{{ STATIC_URL }}css/libs.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/base{% if not debug %}.min{% endif %}.css" rel="stylesheet">
{% block extra_css %}{% endblock %}

<!-- support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="{{ STATIC_URL }}js/ie_fix.js"></script>
<![endif]-->
<script src="{{ STATIC_URL }}js/libs.js"></script>
<script src="{{ STATIC_URL }}js/common{% if not debug %}.min{% endif %}.js"></script>
<script src="{{ STATIC_URL }}js/account{% if not debug %}.min{% endif %}.js"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

src/templates/pattern.html
{% extends 'base.html' %}
{% load webdesign %}

{% block title %}Выбор шаблона - Redstack{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/pattern.css">
{% endblock %}

{% block ng-app %}PatternApp{% endblock %}

{% block main %}
    <div class="page_wrap">
        <div class="container">
            <div class="row title_wrap">
                <div class="col-md-12 text-center">
                    <h1>Выбор шаблона</h1>
                </div>
            </div>
            <form name="PatternForm" ng-submit="submit('{{ request.path }}')" ng-controller="PatternFormCtrl"
                  role="form">
                <div class="row input_wrap">
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-3 field">
                            <input name="site_name" type="text" class="form-control site_name"
                                   ng-model="formData.site_name" placeholder="Название сайта" required>
                        </div>
                        <div class="col-md-2 field">
                            <button class="btn btn-success btn-block" type="button" ng-click="generate_name()">
                                Случайное
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row pattern_wrap" ng-init="img_count={{ images|length }}">
                    {% for image in images %}
                        <div class="col-xs-12 col-md-4 pw_item">
                            <img src="{{ STATIC_URL }}img/{{ image.path }}" ng-class="blurs.{{ forloop.counter0 }}"
                                 ng-mouseenter="active({{ forloop.counter0 }})" ng-mouseleave="deactive()"
                                 ng-click="set_img('{{ image.val }}')" class="img-rounded img-responsive">
                            <input type="radio" name="site_template" ng-checked="formData.site_template"
                                   ng-model="formData.site_template" value="{{ image.val }}"
                                   ng-required="!formData.site_template">
                        </div>
                    {% endfor %}
                </div>
                <div class="row button_wrap">
                    <div class="col-md-2 col-md-offset-5">
                        <button class="btn btn-success btn-block btn-submit-pattern ladda-button"
                                ng-disabled="PatternForm.$invalid" data-style="zoom-out">
                            <span class="ladda-label">Создать</span>
                            <span class="ladda-spinner"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}js/pages/pattern/pattern.js"></script>
    <script src="{{ STATIC_URL }}js/pages/pattern/factory.js"></script>
{% endblock %}